### ISSUE TITLE
Identification of shaders

### ISSUE THREAD

**Issue by benjymous** [spite/ShaderEditorExtension#10]
Is there a simple way I can tag my shaders, so that the UI knows what each one is? (I.e. sticking some sort of comment at the top of the source, so it can show "Main", "Post Process", "Overlay", etc rather than "Program 0", "Program 1", "Program 2")

**Comment by spite** [comment]
It would be great to have a feature like that, but I don't see how it could be done so the labels stay between reloads.

The WebGLPrograms don't have an easily identifiable trait. I'm adding a UUID, but that changes every time a program is created, so it's not consistent across sessions.

The order of creation looks like it's reliable, but it might change if the shaders are created from files downloaded from a network, or if they depend on loading a model, etc.

Storing a reference to the combination of vertex shader source and fragment shader source might work, but it sounds very brittle as a solution. There might be something to investigate there.

In the mean time, the option is to use shader highlighting, but it's disabled at the moment since it's creating problems. Once it's fixed it'll be easier to identify each shader.

**Comment by benjymous** [comment]
You could just take the first comment in the vertex shader source to be the name, I guess (or look for a comment with a specific prefix)

**Comment by spite** [comment]
It's working since this commit https://github.com/spite/ShaderEditorExtension/commit/74dbb90a19831ac88b2d1580c252b52b7e65bb4e. I've opened a discussion on a [gist here](https://gist.github.com/spite/7ae92212b4f28076ba29) to discuss how it works and if it would be good to try to standarise it

**Comment by spite** [comment]
Ok. Based on [the discussion here](https://gist.github.com/spite/7ae92212b4f28076ba29), this is how it's implemented:
- #define SHADER_NAME {name} to specify name for the shader in an ASCII string
  ![screen shot 2015-06-25 at 15 45 39](https://cloud.githubusercontent.com/assets/731885/8355787/9603e834-1b51-11e5-801d-4901bf536106.png)
- #define SHADER_NAME_B64 {name} to specify in a base64-encoded UTF-8 string
  ![screen shot 2015-06-25 at 15 44 50](https://cloud.githubusercontent.com/assets/731885/8355793/9a94870a-1b51-11e5-8ac2-21839f4ec106.png)
