### ISSUE TITLE
Make highlighting optional?

### ISSUE THREAD

**Issue by ebraminio** [spite/ShaderEditorExtension#15]
1. Open https://www.shadertoy.com/view/MsjSW3
2. Highlight a shader
3. The demo stops.

I don't know about its reason, maybe it would be reasonable to provide highlighting feature not by default set on feature? http://madebyevan.com/webgl-water/ causes severe kernel issues on my system so not highlighting at the first place would be nice I think.

![UI](https://cloud.githubusercontent.com/assets/833473/7672600/07ec80f4-fd0d-11e4-96c6-2848ffd0e361.png)

This is just a suggestion but if you can fix https://www.shadertoy.com/view/MsjSW3 issue, I think making highlighting optional (my suggestion) would not that much reasonable.

**Comment by spite** [comment]
Yes, I've been thinking about that. 

The main issue is, of course, that some pages are stopping working, like ShaderToy. I'm working on that trying to figure it out. I think it's related to shader compilation, not to shader highlighting.

In the case of Evan's WebGL Water it's because he's using some FBOs to encode data, and the highlighting messes with those calculations.

Anyway, in the meantime, there's a disabling option with this commit https://github.com/spite/ShaderEditorExtension/commit/260c599f9640790cc3f19229a077decab84eeae0

Thanks for the feedback! :)

**Comment by ebraminio** [comment]
It looks great! Thank you
